### ISSUE TITLE
Failed to parse classes compiled using Java 21

### ISSUE THREAD

**Issue by 3TUSK** [node3112/kirjava#6]
https://github.com/notiska/kirjava/blob/992bf6e7508f3828217830b7751f5b6f367127d1/src/kirjava/version.py#L106-L109

There is no `65` in the `NAMES` list. Java 21 has major version of `65`. 

Attempting to read a class file with major version of 65 will lead to a `KeyError` at `self.NAMES[major]`. 

Perhaps we can also have Java 22/23 added into the list as well?

**Comment by notiska** [comment]
Ah really sorry for the delay, I'll add the later versions of Java now.

**Comment by notiska** [comment]
Should be fixed now, thanks for the report.
Again sorry for the delay, will be checking more frequently.
